projetossp/config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :resquest_types
  resources :image_reports
  resources :question_resquest_criminals
  #resources :questions

  get 'reports/index', to: 'reports#index', as: :reports_index

  # Requisição e laudo
  resources :resquest_criminals do 
    resources :reports
    resources :questions
  end

  get 'reports/all', to: 'reports#general', as: :reports
  resources :districts
  resources :group_permissions
  resources :user_permissions
  resources :segments
  resources :user_groups
  resources :permissions

  get 'auditor/index'
  get 'auditor/show/:id', to: 'auditor#show', as: :show_auditor
  get 'images_for_report/index'
  get 'users/change_approved/:id', to: 'users#change_approved', as: :change_approved

  resources :people
  devise_for :users

  scope "/administrador" do
    resources :users
  end

  root to: 'home#index'
  get '/about', to: 'home#about', as: :about
  get '/contact', to: 'home#contact', as: :contact
  get '/dashboard', to: 'home#index', as: :dashboard

end

projetossp/app/models/group_permission.rb
class GroupPermission < ActiveRecord::Base
  
  # GroupPermission entidade que consende permissão
  # de um grupo expecífico a um módulo
  # Exemplo:
  # =>  UserGroup.new = delegado
  # =>  Segment.new = person
  # =>  Permission = index
  
  # Injeção de funções de auditória
  audited
  is_impressionable
  
  # Relacionamentos
  belongs_to :user_group
  belongs_to :segment
  belongs_to :permission
end

projetossp/app/controllers/group_permissions_controller.rb
class GroupPermissionsController < ApplicationController
  before_action :set_group_permission, only: [:show, :edit, :update, :destroy]

  # GET /group_permissions
  # GET /group_permissions.json
  def index
    authorize :group_permission, :index?
    @group_permissions = GroupPermission.all
  end

  # GET /group_permissions/1
  # GET /group_permissions/1.json
  def show
    authorize :group_permission, :show?
  end

  # GET /group_permissions/new
  def new
    authorize :group_permission, :new?
    @group_permission = GroupPermission.new
  end

  # GET /group_permissions/1/edit
  def edit
    authorize :group_permission, :edit?
  end

  # POST /group_permissions
  # POST /group_permissions.json
  def create
    authorize :group_permission, :create?
    @group_permission = GroupPermission.new(group_permission_params)

    respond_to do |format|
      if @group_permission.save
        format.html { redirect_to @group_permission, notice: 'Group permission was successfully created.' }
        format.json { render :show, status: :created, location: @group_permission }
      else
        format.html { render :new }
        format.json { render json: @group_permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_permissions/1
  # PATCH/PUT /group_permissions/1.json
  def update
    authorize :group_permission, :update?
    respond_to do |format|
      if @group_permission.update(group_permission_params)
        format.html { redirect_to @group_permission, notice: 'Group permission was successfully updated.' }
        format.json { render :show, status: :ok, location: @group_permission }
      else
        format.html { render :edit }
        format.json { render json: @group_permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_permissions/1
  # DELETE /group_permissions/1.json
  def destroy
    authorize :group_permission, :destroy?
    @group_permission.destroy
    respond_to do |format|
      format.html { redirect_to group_permissions_url, notice: 'Group permission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_permission
      @group_permission = GroupPermission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_permission_params
      params.require(:group_permission).permit(:user_group_id, :segment_id, :permission_id)
    end
end

projetossp/app/helpers/group_permissions_helper.rb
module GroupPermissionsHelper
end

projetossp/app/views/group_permissions/_form.html.erb
<div class="ui form">
  <h4 class="ui dividing header">Informações</h4>
  <%= form_for(@group_permission) do |f| %>
    <% if @group_permission.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@group_permission.errors.count, "error") %> prohibited this group_permission from being saved:</h2>
  
        <ul>
        <% @group_permission.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= f.label :user_group_id %><br>
      <%= f.collection_select(:user_group_id, UserGroup.all, :id, :function, {}, {:class=>'ui search dropdown'}) %>
    </div>
    <div class="field">
      <%= f.label :segment_id %><br>
      <%= f.collection_select(:segment_id, Segment.all, :id, :name, {}, {:class=>'ui search dropdown'}) %>
    </div>
    <div class="field">
      <%= f.label :permission_id %><br>
      <%= f.collection_select(:permission_id, Permission.all, :id, :name, {}, {:class=>'ui search dropdown'}) %>
    </div>
    <div class="actions">
      <%= f.submit class:'ui teal button' %>
    </div>
  <% end %>
</div>

projetossp/app/views/group_permissions/edit.html.erb
<h1>Editing Group Permission</h1>

<%= render 'form' %>

<%= link_to 'Detalhes', @group_permission, class: 'ui button' %> 
<%= link_to 'Voltar', group_permissions_path, class: 'ui button' %>

projetossp/app/views/group_permissions/index.html.erb
<h1 class"ui header">Lista de permissão de grupo</h1>
  <table class='ui orange table '>
  <thead>
    <tr>
      <th>Grupo de Usuário</th>
      <th>Módulo</th>
      <th>Permissão</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @group_permissions.each do |group_permission| %>
      <tr>
        <td><%= group_permission.user_group.function %></td>
        <td><%= group_permission.segment.name %></td>
        <td><%= group_permission.permission.name %></td>
        <td><%= link_to 'Detalhes', group_permission, class: 'ui tiny blue basic button' %></td>
        <td><%= link_to 'Editar', edit_group_permission_path(group_permission), class: 'ui tiny blue basic button' %></td>
        <td><%= link_to 'Excluir', group_permission, method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui tiny red basic button' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo grupo de permissão', new_group_permission_path, class: 'ui teal button' %>

projetossp/app/views/group_permissions/new.html.erb
<h1>New Group Permission</h1>

<%= render 'form' %>

<%= link_to 'Voltar', group_permissions_path, class: 'ui button' %>

projetossp/app/views/group_permissions/show.html.erb
<div class='ui padded center aligned teal  segment show'>
 <p>
    <strong>Grupo de usuário:</strong>
    <%= @group_permission.user_group.function %>
  </p>
  
  <p>
    <strong>Módulo:</strong>
    <%= @group_permission.segment.name %>
  </p>
  
  <p>
    <strong>Permissão:</strong>
    <%= @group_permission.permission.name %>
  </p>
  
  <%= link_to 'Editar', edit_group_permission_path(@group_permission), class: 'ui button' %> 
  <%= link_to 'Voltar', group_permissions_path, class: 'ui button' %>
</div>