projetossp/config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :resquest_types
  resources :image_reports
  resources :question_resquest_criminals
  #resources :questions

  get 'reports/index', to: 'reports#index', as: :reports_index

  # Requisição e laudo
  resources :resquest_criminals do 
    resources :reports
    resources :questions
  end

  get 'reports/all', to: 'reports#general', as: :reports
  resources :districts
  resources :group_permissions
  resources :user_permissions
  resources :segments
  resources :user_groups
  resources :permissions

  get 'auditor/index'
  get 'auditor/show/:id', to: 'auditor#show', as: :show_auditor
  get 'images_for_report/index'
  get 'users/change_approved/:id', to: 'users#change_approved', as: :change_approved

  resources :people
  devise_for :users

  scope "/administrador" do
    resources :users
  end

  root to: 'home#index'
  get '/about', to: 'home#about', as: :about
  get '/contact', to: 'home#contact', as: :contact
  get '/dashboard', to: 'home#index', as: :dashboard

end

projetossp/app/models/district.rb
class District < ActiveRecord::Base
    
    # Injeção de funções de auditória
    audited
    is_impressionable
    
    # Relacionamentos
    belongs_to :district
    has_many :districts
    
    # Distritos superiores
    def fathers_districts
        fathers_districts  = Array.new
        current_district = self
        while current_district
            fathers_districts << current_district
            current_district = current_district.district
        end
        
        return fathers_districts.reverse
    end
    
    # Distritos subordinados 
    def get_ancestors result = Array.new
        result << self
        unless self.districts.empty?
            self.districts.each do |district|
              district.get_ancestors(result)
            end
        end
        return result
    end
    
    # Lista de distritos
    def list_district
        unless self.id 
            District.all
        else
            District.where.not(id: self.id) 
        end
    end
end

projetossp/app/controllers/districts_controller.rb
class DistrictsController < ApplicationController
  before_action :set_district, only: [:show, :edit, :update, :destroy]

  # GET /districts
  # GET /districts.json
  def index
    authorize :district, :index?
    @districts = District.all
  end

  # GET /districts/1
  # GET /districts/1.json
  def show
    authorize :district, :show?
  end

  # GET /districts/new
  def new
    authorize :district, :new?
    @district = District.new
  end

  # GET /districts/1/edit
  def edit
    authorize :district, :edit?
  end

  # POST /districts
  # POST /districts.json
  def create
    authorize :district, :create?
    @district = District.new(district_params)

    respond_to do |format|
      if @district.save
        format.html { redirect_to @district, notice: 'District was successfully created.' }
        format.json { render :show, status: :created, location: @district }
      else
        format.html { render :new }
        format.json { render json: @district.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /districts/1
  # PATCH/PUT /districts/1.json
  def update
    authorize :district, :update?
    respond_to do |format|
      if @district.update(district_params)
        format.html { redirect_to @district, notice: 'District was successfully updated.' }
        format.json { render :show, status: :ok, location: @district }
      else
        format.html { render :edit }
        format.json { render json: @district.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /districts/1
  # DELETE /districts/1.json
  def destroy
    authorize :district, :destroy?
    @district.destroy
    respond_to do |format|
      format.html { redirect_to districts_url, notice: 'District was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_district
      @district = District.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def district_params
      params.require(:district).permit(:district_id, :name, :public_place, :city, :state, :cep, :phone, :email, :neighborhood, :second_phone)
    end
end

projetossp/app/helpers/districts_helper.rb
module DistrictsHelper
end

projetossp/app/views/districts/_form.html.erb
<div class="ui form">
  <h4 class="ui dividing header">Informações</h4>
  <%= form_for(@district) do |f| %>
    <% if @district.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@district.errors.count, "error") %> prohibited this district from being saved:</h2>
  
        <ul>
        <% @district.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= f.label :district_id %><br>
      <%= f.collection_select(:district_id, @district.list_district, :id, :name, {:prompt=>true}, {:class=>'ui search dropdown'}) %>
    </div>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :public_place %><br>
      <%= f.text_field :public_place %>
    </div>
    <div class="field">
      <%= f.label :city %><br>
      <%= f.text_field :city %>
    </div>
    <div class="field">
      <%= f.label :state %><br>
      <%= f.text_field :state %>
    </div>
    <div class="field">
      <%= f.label :cep %><br>
      <%= f.text_field :cep %>
    </div>
    <div class="field">
      <%= f.label :phone %><br>
      <%= f.text_field :phone %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :neighborhood %><br>
      <%= f.text_field :neighborhood %>
    </div>
    <div class="field">
      <%= f.label :second_phone %><br>
      <%= f.text_field :second_phone %>
    </div>
    <div class="actions">
      <%= f.submit class:'ui teal button' %>
    </div>
  <% end %>
  
</div>
<script>
    $('select.dropdown').dropdown();
</script>

projetossp/app/views/districts/edit.html.erb
<h1>Editar distrito</h1>

<%= render 'form' %>

<%= link_to 'Detalhes', @district, class: 'ui button' %> 
<%= link_to 'Voltar', districts_path, class: 'ui button' %>

projetossp/app/views/districts/index.html.erb
<h1 class"ui header">Lista de orgãos</h1>
  <table class='ui orange table '>
    <thead>
      <tr>
        <th>Distrito Superior</th>
        <th>Nome</th>
        <th>Logradouro</th>
        <th>Cidade</th>
        <th>Telefone</th>
        <th>Email</th>
        <th>Segundo Telefone</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @districts.each do |district| %>
        <tr>
          <td><%= district.district.name unless district.district.nil?  %></td>
          <td><%= district.name %></td>
          <td><%= district.public_place %></td>
          <td><%= district.city %></td>
          <td><%= district.phone %></td>
          <td><%= district.email %></td>
          <td><%= district.second_phone %></td>
          <td><%= link_to 'Detalhes', district, class: 'ui tiny blue basic button' %></td>
          <td><%= link_to 'Editar', edit_district_path(district), class: 'ui tiny blue basic button' %></td>
          <td><%= link_to 'Excluir', district, method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui tiny red basic button' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<br>

<%= link_to 'Novo Orgão', new_district_path, class: 'ui teal button' %>

projetossp/app/views/districts/new.html.erb
<h1>Novo distrito</h1>

<%= render 'form' %>

<%= link_to 'Voltar', districts_path, class: 'ui button' %>

projetossp/app/views/districts/show.html.erb
<div class='ui padded center aligned teal segment show'>
  <p>
    <strong>Distrito superior:</strong>
    <%= @district.district.name unless @district.district.nil? %>
  </p>
  
  <p>
    <strong>Nome:</strong>
    <%= @district.name %>
  </p>
  
  <p>
    <strong>Logradouro:</strong>
    <%= @district.public_place %>
  </p>
  
  <p>
    <strong>Cidade:</strong>
    <%= @district.city %>
  </p>
  
  <p>
    <strong>Estado:</strong>
    <%= @district.state %>
  </p>
  
  <p>
    <strong>Cep:</strong>
    <%= @district.cep %>
  </p>
  
  <p>
    <strong>Telefone:</strong>
    <%= @district.phone %>
  </p>
  
  <p>
    <strong>Email:</strong>
    <%= @district.email %>
  </p>
  
  <p>
    <strong>Bairro:</strong>
    <%= @district.neighborhood %>
  </p>
  
  <p>
    <strong>Segundo Telefone:</strong>
    <%= @district.second_phone %>
  </p>

  <%= link_to 'Editar', edit_district_path(@district), class: 'ui button' %> 
  <%= link_to 'Voltar', districts_path, class: 'ui button' %>
</div>

<div class="ui blue segment">
  <div class='header'>Subordinado</div>
  <div class="ui middle aligned divided list">
      <% @district.fathers_districts.each do |district| %>
        <div class="item">
            <div class="right floated content">
              <%= link_to 'Detalhes', district_path(district), class: "ui button"  %>
            </div>
            <div class="content">
              <%= district.name %>
            </div>
        </div>
      <% end %>
  </div>
</div>

<div class="ui orange segment">
  <div class='header'>
    <h5>Superior</h5>
  </div>
  <div class="ui middle aligned divided list">
      <% @district.get_ancestors.each do |district| %>
        <div class="item">
            <div class="right floated content">
              <%= link_to 'Detalhes', district_path(district), class: "ui button"  %>
            </div>
            <div class="content">
              <%= district.name %>
            </div>
        </div>
      <% end %>
  </div>
</div>