projetossp/config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :resquest_types
  resources :image_reports
  resources :question_resquest_criminals
  #resources :questions

  get 'reports/index', to: 'reports#index', as: :reports_index

  # Requisição e laudo
  resources :resquest_criminals do 
    resources :reports
    resources :questions
  end

  get 'reports/all', to: 'reports#general', as: :reports
  resources :districts
  resources :group_permissions
  resources :user_permissions
  resources :segments
  resources :user_groups
  resources :permissions

  get 'auditor/index'
  get 'auditor/show/:id', to: 'auditor#show', as: :show_auditor
  get 'images_for_report/index'
  get 'users/change_approved/:id', to: 'users#change_approved', as: :change_approved

  resources :people
  devise_for :users

  scope "/administrador" do
    resources :users
  end

  root to: 'home#index'
  get '/about', to: 'home#about', as: :about
  get '/contact', to: 'home#contact', as: :contact
  get '/dashboard', to: 'home#index', as: :dashboard

end

projetossp/app/models/resquest_criminal.rb
class ResquestCriminal < ActiveRecord::Base
  
  enum status: {aberto: 0, em_andamento:1, finalizado: 2} 
  
  # Injeção de funções de auditória
  audited
  is_impressionable
  
  # Relacionamentos
  belongs_to :user
  belongs_to :person
  belongs_to :resquest_type
  belongs_to :district_resquest, class_name: 'District', :foreign_key => 'district_resquest_id'
  belongs_to :district_send, class_name: 'District', :foreign_key => 'district_send_id'
  has_many :question_resquest_criminals
  has_many :questions, through: :question_resquest_criminals
  
  # Retrições de criação e atualização
  validates :district_send, presence: true
  validates :district_resquest, presence: true
  validates :person, presence: true
end

projetossp/app/controllers/resquest_criminals_controller.rb
class ResquestCriminalsController < ApplicationController
  before_action :set_resquest_criminal, only: [:show, :edit, :update, :destroy]

  # GET /resquest_criminals
  # GET /resquest_criminals.json
  def index
    authorize :resquest_criminal, :index?
    @resquest_criminals = ResquestCriminal.all
  end

  # GET /resquest_criminals/1
  # GET /resquest_criminals/1.json
  def show
    authorize :resquest_criminal, :index?
    @questions = @resquest_criminal.questions
  end

  # GET /resquest_criminals/new
  def new
    authorize :resquest_criminal, :new?
    @resquest_criminal = ResquestCriminal.new
  end

  # GET /resquest_criminals/1/edit
  def edit
    authorize :resquest_criminal, :edit?
  end

  # POST /resquest_criminals
  # POST /resquest_criminals.json
  def create
    authorize :resquest_criminal, :create?
    @resquest_criminal = ResquestCriminal.new(resquest_criminal_params)
    
    # Nessa linha a requisição atual é setada com o ID do usuário atual
    @resquest_criminal.user_id = current_user.id
    @resquest_criminal.person_name = Person.find(@resquest_criminal.person_id).name
    @resquest_criminal.district_resquest = current_user.district
    respond_to do |format|
      if @resquest_criminal.save
        questions = Question.where(question_default: true, resquest_type_id: @resquest_criminal.resquest_type_id)
        @resquest_criminal.questions << questions
        format.html { redirect_to @resquest_criminal, notice: 'Resquest criminal was successfully created.' }
        format.json { render :show, status: :created, location: @resquest_criminal }
      else
        format.html { render :new }
        format.json { render json: @resquest_criminal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resquest_criminals/1
  # PATCH/PUT /resquest_criminals/1.json
  def update
    authorize :resquest_criminal, :update?
    respond_to do |format|
      if @resquest_criminal.update(resquest_criminal_params)
        format.html { redirect_to @resquest_criminal, notice: 'Resquest criminal was successfully updated.' }
        format.json { render :show, status: :ok, location: @resquest_criminal }
      else
        format.html { render :edit }
        format.json { render json: @resquest_criminal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resquest_criminals/1
  # DELETE /resquest_criminals/1.json
  def destroy
    authorize :resquest_criminal, :destroy?
    @resquest_criminal.question_resquest_criminals.each do |resquest|
      resquest.destroy
    end
    @resquest_criminal.destroy
    respond_to do |format|
      format.html { redirect_to resquest_criminals_url, notice: 'Resquest criminal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resquest_criminal
      @resquest_criminal = ResquestCriminal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resquest_criminal_params
      params.require(:resquest_criminal).permit(:district_resquest_id, :district_send_id, :user_id, :resquest_type_id, :person_id)
    end
end

projetossp/app/helpers/resquest_criminals_helper.rb
module ResquestCriminalsHelper
end

projetossp/app/views/resquest_criminals/_form.html.erb
<%= form_for(@resquest_criminal) do |f| %>
  <% if @resquest_criminal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resquest_criminal.errors.count, "error") %> prohibited this resquest_criminal from being saved:</h2>

      <ul>
      <% @resquest_criminal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div class="field">-->
    <%# f.label :district_resquest %><br>
    <%# f.number_field :district_resquest %>
  <!--</div>-->
  <div class="field">
    <%= f.label :district_send %><br>
    <%= f.collection_select(:district_send_id, District.all, :id, :name, {}, {:class=>'ui dropdown'}) %>
  </div>
  <!--<div class="field">
    <%# f.label :user_id %><br>
    <%# f.text_field :user_id %>
  </div> Esse campo vai ser removido por conta do usuário atual ser o responsável por esse campo. Veja no controller a solução dessa questão-->
  <div class="field">
    <%= f.label :resquest_type %><br>
    <%# f.select(:type, ResquestCriminal.types.keys, {}) %>
    <%= f.collection_select(:resquest_type_id, ResquestType.all, :id, :name, {:prompt=>false}, {:class=>'ui search dropdown'}) %>
  </div>
  <div class="field">
    <%= f.label :person_id %><br>
    <%= f.collection_select(:person_id, Person.all, :id, :name, {:prompt=>true}, {:class=>'ui search dropdown'}) %>
  </div>
  <div class="actions">
    <%= f.submit class: 'ui teal button' %>
  </div>
<% end %>

projetossp/app/views/resquest_criminals/edit.html.erb
<h1>Editar resquisição </h1>
<%= render 'form' %>

<%= link_to 'Detalhes', @resquest_criminal, class: 'ui button' %> 
<%= link_to 'Voltar', resquest_criminals_path, class: 'ui button' %>

projetossp/app/views/resquest_criminals/index.html.erb
<h1 class"ui header">Lista de requisições</h1>
  <table class='ui orange table '>
  <thead>
    <tr>
      <th>Orgão requisitor</th>
      <th>Orgão destinátario</th>
      <th>Agente</th>
      <th>Tipo</th>
      <th>Pessoa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resquest_criminals.each do |resquest_criminal| %>
      <tr>
        <td><%= resquest_criminal.district_resquest.name %></td>
        <td><%= resquest_criminal.district_send.name %></td>
        <td><%= resquest_criminal.user.name %></td>
        <td><%= resquest_criminal.resquest_type.name %></td>
        <td><%= resquest_criminal.person.name %></td>
        <td><%= link_to 'Detalhes', resquest_criminal, class: 'ui tiny blue basic button' %></td>
        <td><%= link_to 'Editar', edit_resquest_criminal_path(resquest_criminal), class: 'ui tiny blue basic button' %></td>
        <td><%= link_to 'Excluir', resquest_criminal, method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui tiny red basic button' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova requisição', new_resquest_criminal_path, class: 'ui teal button' %>

projetossp/app/views/resquest_criminals/new.html.erb
<h1>Nova requisição</h1>

<%= render 'form' %>

<%= link_to 'Voltar', resquest_criminals_path, class: 'ui button' %>

projetossp/app/views/resquest_criminals/show.html.erb
<div class='ui padded center aligned teal  segment show'>
  <p>
    <strong>Orgão resquisitor:</strong>
    <%= @resquest_criminal.district_resquest.name %>
  </p>
  
  <p>
    <strong>Orgão receptor:</strong>
    <%= @resquest_criminal.district_send.name %>
  </p>
  
  <p>
    <strong>Usuário:</strong>
    <%= @resquest_criminal.user.name %>
  </p>
  
  <p>
    <strong>Tipo de requisição:</strong>
    <%= @resquest_criminal.resquest_type.name %>
  </p>
  
  <p>
    <strong>Pessoa:</strong>
    <%= @resquest_criminal.person.name %>
  </p>
  
  <%= link_to 'Editar', edit_resquest_criminal_path(@resquest_criminal), class: 'ui button' %> 
  <%= link_to 'Voltar', resquest_criminals_path, class: 'ui button' %>
</div>

<div class='ui padded center aligned blue segment show'>
  <%= link_to 'Adicionar Questionamento', new_resquest_criminal_question_path(@resquest_criminal),class: 'ui positive button'%>
</div>

<h1 class"ui header">Lista de questões</h1>
  <table class='ui orange table '>
  <thead>
    <tr>
      <th>Descrição</th>
      <th>Pergunta Padrão</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.description %></td>
        <td><%= (question.question_default) ? 'Sim': 'Não' %></td>
        <td><%= link_to 'Detalhes', resquest_criminal_question_path(@resquest_criminal,question), class: 'ui tiny blue basic button' %></td>
        <td><%= link_to 'Editar', edit_resquest_criminal_question_path(@resquest_criminal,question), class: 'ui tiny blue basic button' %></td>
        <td><%= link_to 'Excluir', resquest_criminal_question_path(@resquest_criminal,question), method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui tiny red basic button' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>