projetossp/config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :resquest_types
  resources :image_reports
  resources :question_resquest_criminals
  #resources :questions

  get 'reports/index', to: 'reports#index', as: :reports_index

  # Requisição e laudo
  resources :resquest_criminals do 
    resources :reports
    resources :questions
  end

  get 'reports/all', to: 'reports#general', as: :reports
  resources :districts
  resources :group_permissions
  resources :user_permissions
  resources :segments
  resources :user_groups
  resources :permissions

  get 'auditor/index'
  get 'auditor/show/:id', to: 'auditor#show', as: :show_auditor
  get 'images_for_report/index'
  get 'users/change_approved/:id', to: 'users#change_approved', as: :change_approved

  resources :people
  devise_for :users

  scope "/administrador" do
    resources :users
  end

  root to: 'home#index'
  get '/about', to: 'home#about', as: :about
  get '/contact', to: 'home#contact', as: :contact
  get '/dashboard', to: 'home#index', as: :dashboard

end

projetossp/app/models/user.rb
class User < ActiveRecord::Base
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  # Usuário recebendo montagem de uploader
  mount_uploader :photo, PhotoUploader

  # Injeção de funções de auditória
  audited
  is_impressionable
  
  # Relacionamentos
  belongs_to :user_group
  belongs_to :district
  has_many :user_permissions

  def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end

  def self.send_reset_password_instructions(attributes={})
    recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
    if !recoverable.approved?
      recoverable.errors[:base] << I18n.t("devise.failure.not_approved")
    elsif recoverable.persisted?
      recoverable.send_reset_password_instructions
    end
    recoverable
  end
  
  # Função de verificação de permissão dentro do módulo
  # da aplicação
  # Exemplo:
  # =>  segment = :person
  # =>  permission = :create
  
  def permission_segment? segment, permission
    segment = Segment.where name: segment
    permission = Permission.where name: permission
    unless user_group.group_permissions.where(segment: segment, permission: permission).empty?
      return true
    end
    
    unless user_permissions.where(segment: segment, permission: permission).empty? 
      return true
    end  
    
    return false
  end
  
end

projetossp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :configure_permitted_parameters, if: :devise_controller?

  # GET /users
  # GET /users.json
  def index
    authorize :user, :index?
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    authorize :user, :show?
  end

  # GET /users/new
  def new
    authorize :user, :new?
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    authorize :user, :edit?
  end

  # POST /users
  # POST /users.json
  def create
    authorize :user, :create?

    @user = User.new(user_params)

    #Pegando hora atual do registro
    @user.registration_date = Time.now

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: t(".notice") }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    authorize :user, :update?

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: t(".notice") }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    authorize :user, :destroy?
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: t(".notice") }
      format.json { head :no_content }
    end
  end

  # Método responsável por alterar o atributo approved do Usuário
  # O atributo approved é responsável por possibilitar o acesso ao sistema
  def change_approved
    authorize :user, :change_approved?
    @user = User.find(params[:id])
    @user.approved = !@user.approved
    @user.save
    respond_to do |format|
      if @user.approved == true
        format.html { redirect_to @user, notice: t(".notice_true") }
        format.json { render :index, status: :ok, location: @user }
      else
        format.html { redirect_to @user, notice: t(".notice_false") }
        format.json { render :index, status: :ok, location: @user }
      end
    end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      #params.fetch(:user, {})
      params.require(:user).permit(:id,:username, :email, :salt, :encrypted_password,:name, :district_id,:user_group_id, :registration)
    end
end

projetossp/app/helpers/users_helper.rb
module UsersHelper
end

projetossp/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">  
          <%= f.label :name %><br />
          <%= f.text_field :name, autofocus: true, placeholder: "Digite seu nome" %>
      </div>

      <div class="four wide field">
          <%= f.label :photo %><br>
          <%= f.file_field :photo %>
          <%= f.hidden_field :photo_cache %>
      </div>

      <div class="field">  
          <%= f.label :email %><br />
          <%= f.email_field :email, placeholder: "Digite seu melhor E-mail" %>
      </div>
      
      <div class="field">  
          <%= f.label :user_group_id %><br />
          <%= f.collection_select(:user_group_id, UserGroup.all, :id, :description, {}, {class: 'ui dropdown'}) %>
      </div>

      <div class="field">  
          <%= f.label :registration %><br />
          <%= f.text_field :registration, placeholder: "Digite sua matricula" %>
      </div>

      <div class="field">  
          <%= f.label :district_id %><br />
          <%= f.collection_select(:district_id, District.all, :id, :name,{}, class:'ui dropdown') %>
          
      </div>

      <div class="field">
        <%# f.label :password %>
        <%# if @minimum_password_length %>
        <%# @minimum_password_length %>
        <%# end %><br />
        <%# f.password_field :password, autocomplete: "off" %>
      </div>

      <div class="field">
        <%# f.label :password_confirmation %><br />
        <%# f.password_field :password_confirmation, autocomplete: "off" %>
      </div>

  <div class="actions">
    <%= f.submit class: 'ui teal button' %>
  </div>
<% end %>

projetossp/app/views/users/edit.html.erb
<br>
<h1 class="ui header">Editando Usuário</h1>
<div class="ui form">
    <%= render 'form' %>
</div>
<%= link_to 'Detalhes', @user, class: 'ui button' %> 
<%= link_to 'Voltar', users_path, class: 'ui button' %>

projetossp/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t(".title")%></h1>

<table class="ui orange table">
  <thead>
    <tr>
      <th>E-mail</th>
      <th>Aprovado</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        
          <td><%= user.email %></td>
          <% if user.approved %>
          <td>Sim</td>
          <td><%= link_to 'Desaprovar usuário', change_approved_path(user), class: 'ui tiny blue basic button ' %></td>
          <% else %>
          <td>Não</td>
          <td><%= link_to 'Aprovar usuário', change_approved_path(user), class: 'ui tiny blue basic button ' %></td>
          <% end %>
        <td><%= link_to 'Editar', edit_user_path(user), class: 'ui tiny blue basic button ' %></td>
        <td><%= link_to 'Ver', user, class: 'ui tiny blue basic button ' %></td>
        <td><%= link_to 'Excluir', user, method: :delete, data: { confirm: 'Você tem certeza?'}, class: 'ui tiny red basic button ' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

projetossp/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

projetossp/app/views/users/show.html.erb
  <p>
	<div class="ui items">

	<div class="item">

    <% if @user.photo? %>    
      <div class="ui small image">
          <%= image_tag(@user.photo_url) %>
      </div>
    <% else %>
      <div class="ui small image">
        <img src="/Images/avatar.png">
      </div>
    <% end %>

    <div class="content">
      
      <div class="header">Nome</div>
      
      <div class="meta">
        <p>
          <strong>Nome:</strong>
          <%= @user.name %>
        </p>
        <p>
        	<strong>E-mail:</strong>
	    		<%= @user.email %>
        </p>
        <p>
          <strong>Cargo:</strong>
          <%= @user.user_group.description %>
        </p>
        <p>
          <strong>Matricula:</strong>
          <%= @user.registration %>
        </p>
        <p>
          <strong>Distrito:</strong>
          <%= @user.district.name %>
        </p>
	  	  <p>        	
			    <strong>Aprovado:</strong>
			    <% if @user.approved %>
            Sim
          <% else %>
            Não         
          <% end %>       
        </p>
      </div>

      <div class="description">
        <p></p>
      </div>
    </div>
  </div>



  </div>

	<%= link_to 'Voltar', users_path,  class: 'ui tiny blue basic button ' %>
  </p>